### PR TITLE
Upgrading versions

### PR DESCRIPTION
**Pull request by humbertodias**
ubuntu 18.04
infludb 1.5.2
chronograf 1.4.4.2 - https://docs.influxdata.com/influxdb/v1.4/tools/web_admin
grafana 5.1.0
nodejs 10

grafana5

chronograf

### CODE REVIEW

**Comment by philhawthorne** [comment]
Nice! Can't wait to test this out

**Comment by asantaga** [comment]
oooo lovely! I'll try it out now.

**Comment by philhawthorne** [comment]
I've merged this to the dev branch while I test this out.

If you would like to test this out too, you can use `philhawthorne/docker-influxdb-grafana:edge` to run this.

Thanks @humbertodias

**Comment by urothis** [comment]
Unable to access influxdb with edge image.

**Comment by jezzalencko** [comment]
Hi Phi, total n00b here but I installed your image that has InfluxDB version 1.2 and Grafana 4.1.1 on it, but am having some version difficulties and have no idea how to seamlessly upgrade to the latest version of these in Synology without losing all my data. Can you please help, with some instructions?

**Pull request merged**
