### PR TITLE
Use debian:stretch-slim instead of ubuntu.

### PR DESCRIPTION
**Pull request by dcsg**
The ubuntu image is double the size of `debian:stretch-slim`

### CODE REVIEW

**Comment by philhawthorne** [comment]
Thanks @dcsg 

There seems to be conflicts now with this one.

Have you had any issues using this base image instead of Ubuntu?

**Comment by dcsg** [comment]
It shouldn't have issues, but I just started using this base image today. Give me a couple of days and I can tell you how it is going.

**Comment by philhawthorne** [comment]
Awesome!

Thanks for your PR's

**Comment by dcsg** [comment]
Shall this get merged or should I close it?

**Comment by philhawthorne** [comment]
Sorry mate! I'll test this out soon once my entity IDs in Home Assistant have settled down. If no issues I'll merge this!

Cheers

**Comment by philhawthorne** [comment]
Looks good to me! Cheers

**Pull request merged**
