### PR TITLE
Update README.md and Upgrade Grafana, InfluxDb and ChronoGraf versions 

### PR DESCRIPTION
**Pull request by diogopms**
The goal of this PR it's try to enable the InfluxDb authentication for the future.

If we want to deploy this docker image in the cloud **we can't expose the 8086 without authentication to the internet,**

### CODE REVIEW

**Comment by philhawthorne** [comment]
Thanks @diogopms 

Just to confirm, this PR won't enable SSL by default for users, correct? I can see you've just updated the readme on how to do it

**Comment by diogopms** [comment]
Yes, for now it’s only the readme update I can continue working on this pr and try to enable the authentication.

**Comment by philhawthorne** [comment]
It sounds like the user will need to change the influxDB conf file to enable SSL. Is that right?

If that is the case, it might be possible to do this with:

1. User downloads the influxdb conf file from this repo
2. In the `docker run` mounts it to the required location. An example docker run is below

```bash
docker run -d \
  --name docker-influxdb-grafana \
  -p 3003:3003 \
  -p 3004:8888 \
  -p 8086:8086 \
  -v /path/for/influxdb:/var/lib/influxdb \
  -v /path/for/grafana:/var/lib/grafana \
 -v /path/for/influxdb.conf:/etc/influxdb/influxdb.conf
  philhawthorne/docker-influxdb-grafana:latest
```

This would essentially allow the user to run a complete customised version of Influx. Will that work?

**Comment by diogopms** [comment]
Hey @philhawthorne it's not SSL, but it's database user authentication.

In the current version of this docker image, Influx DB has no password.
https://github.com/philhawthorne/docker-influxdb-grafana/blob/master/influxdb/influxdb.conf#L215

If we expose the Influx DB to the Internet (port: 8086), we should have a user and password.

**Comment by philhawthorne** [comment]
Ah yes I see what you're saying.

I think my comment should still work. By adding `-v /path/for/influxdb.conf:/etc/influxdb/influxdb.conf` to the `docker run` the user will have complete control over those settings.

I'll merge this PR, and then update the wording for clarification on how this can be done 👍

**Pull request closed without merging**
